<?php

$title = 'View Order '.$id;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<br>
<table class="table table-striped">
    <tr><th>Item</th>
        <th>Quantity</th>
        <th>Price</th>
    </tr>
    <?php $grandtotal = 0; ?>
    <?php foreach ($current as $item) : ?>

        <tr>
            <td><?php echo $this->escapeHtml($item->name); ?></td>
            <td>
                <?php echo $this->escapeHtml($item->quantity); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($item->price * $item->quantity);
                $grandtotal += $item->price * $item->quantity;
                ?>
            </td>

        </tr>
    <?php endforeach; ?>
    <tr>
        <td><b>GRAND TOTAL</b></td>
        <td></td>
        <td><?php echo $grandtotal; ?></td>
    </tr>
</table>
<form method="post">
    <input class="btn btn-primary btn-sm" type="submit" name="done" value = "Done">
</form>